# Generated by Django 4.0 on 2021-12-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0003_auto_20211227_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('email', models.EmailField(default='email', max_length=50)),
                ('phone', models.IntegerField(default='0', max_length=20)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
