# Generated by Django 4.0 on 2021-12-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0011_book_category_subcategory_delete_book_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='edition',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
