# Generated by Django 4.0 on 2022-01-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0015_alter_book_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(default='', upload_to='book_images/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default='', upload_to='cat_images/'),
        ),
    ]
