# Generated by Django 4.0 on 2022-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0016_alter_book_book_image_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_desc',
            field=models.TextField(max_length=1000),
        ),
    ]
