# Generated by Django 4.0 on 2022-01-02 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0018_alter_book_price_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
