# Generated by Django 4.0 on 2022-01-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('display', '0020_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Name', max_length=50)),
                ('bio', models.CharField(default='Your Bio', max_length=200)),
                ('phone', models.IntegerField(default=0)),
                ('address', models.CharField(default='Your address', max_length=200)),
                ('photo', models.ImageField(default='static/image/user.png', upload_to='profile_image/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
