# Generated by Django 4.0 on 2022-01-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0026_alter_bookorder_order_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomPayment',
        ),
    ]
