# Generated by Django 4.0 on 2022-01-18 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('display', '0027_delete_roompayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0)),
                ('month', models.IntegerField()),
                ('start_date', models.DateField()),
                ('upto_date', models.DateField()),
                ('payment_id', models.CharField(default='null', max_length=200)),
                ('table_block', models.CharField(default='defaults', max_length=10)),
                ('seat_alloted', models.CharField(default='defaults', max_length=20)),
                ('transaction_status', models.CharField(default='defaults', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
