# Generated by Django 4.0 on 2022-01-24 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0028_roompayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
